# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *

import res2_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 432)
        self.action_New_File = QAction(MainWindow)
        self.action_New_File.setObjectName(u"action_New_File")
        self.action_New_Window = QAction(MainWindow)
        self.action_New_Window.setObjectName(u"action_New_Window")
        self.action_Open_File = QAction(MainWindow)
        self.action_Open_File.setObjectName(u"action_Open_File")
        self.action_Open_Folder = QAction(MainWindow)
        self.action_Open_Folder.setObjectName(u"action_Open_Folder")
        self.action_Open_Workspace = QAction(MainWindow)
        self.action_Open_Workspace.setObjectName(u"action_Open_Workspace")
        self.action_Open_Recent = QAction(MainWindow)
        self.action_Open_Recent.setObjectName(u"action_Open_Recent")
        self.action_Open_File_2 = QAction(MainWindow)
        self.action_Open_File_2.setObjectName(u"action_Open_File_2")
        self.action_Open_Folder_2 = QAction(MainWindow)
        self.action_Open_Folder_2.setObjectName(u"action_Open_Folder_2")
        self.action_Open_Workspace_2 = QAction(MainWindow)
        self.action_Open_Workspace_2.setObjectName(u"action_Open_Workspace_2")
        self.action_Open_Recent_2 = QAction(MainWindow)
        self.action_Open_Recent_2.setObjectName(u"action_Open_Recent_2")
        self.action_Add_Folder_to_Workspace = QAction(MainWindow)
        self.action_Add_Folder_to_Workspace.setObjectName(u"action_Add_Folder_to_Workspace")
        self.action_Save_Workspace_As = QAction(MainWindow)
        self.action_Save_Workspace_As.setObjectName(u"action_Save_Workspace_As")
        self.action_Save = QAction(MainWindow)
        self.action_Save.setObjectName(u"action_Save")
        self.action_Save_As = QAction(MainWindow)
        self.action_Save_As.setObjectName(u"action_Save_As")
        self.action_Save_All = QAction(MainWindow)
        self.action_Save_All.setObjectName(u"action_Save_All")
        self.action_Auto_Save = QAction(MainWindow)
        self.action_Auto_Save.setObjectName(u"action_Auto_Save")
        self.action_Preferences = QAction(MainWindow)
        self.action_Preferences.setObjectName(u"action_Preferences")
        self.actionRevert_File = QAction(MainWindow)
        self.actionRevert_File.setObjectName(u"actionRevert_File")
        self.action_Close_Editor = QAction(MainWindow)
        self.action_Close_Editor.setObjectName(u"action_Close_Editor")
        self.action_Close_Workspace = QAction(MainWindow)
        self.action_Close_Workspace.setObjectName(u"action_Close_Workspace")
        self.action_Close_Window = QAction(MainWindow)
        self.action_Close_Window.setObjectName(u"action_Close_Window")
        self.action_Exit = QAction(MainWindow)
        self.action_Exit.setObjectName(u"action_Exit")
        icon = QIcon()
        icon.addFile(u":/img/img/exit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Exit.setIcon(icon)
        self.action_Undo = QAction(MainWindow)
        self.action_Undo.setObjectName(u"action_Undo")
        self.action_Redo = QAction(MainWindow)
        self.action_Redo.setObjectName(u"action_Redo")
        self.action_Cut = QAction(MainWindow)
        self.action_Cut.setObjectName(u"action_Cut")
        self.action_Copy = QAction(MainWindow)
        self.action_Copy.setObjectName(u"action_Copy")
        self.action_Paste = QAction(MainWindow)
        self.action_Paste.setObjectName(u"action_Paste")
        self.action_Find = QAction(MainWindow)
        self.action_Find.setObjectName(u"action_Find")
        self.action_Replace = QAction(MainWindow)
        self.action_Replace.setObjectName(u"action_Replace")
        self.action_Find_in_Files = QAction(MainWindow)
        self.action_Find_in_Files.setObjectName(u"action_Find_in_Files")
        self.action_Replace_in_Files = QAction(MainWindow)
        self.action_Replace_in_Files.setObjectName(u"action_Replace_in_Files")
        self.action_Toggle_line_Comment = QAction(MainWindow)
        self.action_Toggle_line_Comment.setObjectName(u"action_Toggle_line_Comment")
        self.action_Toggle_Block_Comment = QAction(MainWindow)
        self.action_Toggle_Block_Comment.setObjectName(u"action_Toggle_Block_Comment")
        self.action_Emmet_Expand_Abbreviation = QAction(MainWindow)
        self.action_Emmet_Expand_Abbreviation.setObjectName(u"action_Emmet_Expand_Abbreviation")
        self.action_Emmet = QAction(MainWindow)
        self.action_Emmet.setObjectName(u"action_Emmet")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(0, 10, 641, 121))
        self.groupBox.setStyleSheet(u"background-image: url(:/styles/style.txt);")
        self.dial = QDial(self.groupBox)
        self.dial.setObjectName(u"dial")
        self.dial.setGeometry(QRect(10, 20, 91, 91))
        self.progressBar = QProgressBar(self.groupBox)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(110, 50, 191, 23))
        self.progressBar.setValue(24)
        self.verticalSlider = QSlider(self.groupBox)
        self.verticalSlider.setObjectName(u"verticalSlider")
        self.verticalSlider.setGeometry(QRect(310, 10, 20, 101))
        self.verticalSlider.setOrientation(Qt.Vertical)
        self.doubleSpinBox = QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox.setObjectName(u"doubleSpinBox")
        self.doubleSpinBox.setGeometry(QRect(340, 50, 62, 22))
        self.horizontalSlider = QSlider(self.groupBox)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setGeometry(QRect(410, 50, 151, 22))
        self.horizontalSlider.setOrientation(Qt.Horizontal)
        self.spinBox = QSpinBox(self.groupBox)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(570, 50, 42, 22))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 21))
        self.menu_File = QMenu(self.menubar)
        self.menu_File.setObjectName(u"menu_File")
        self.menu_Edit = QMenu(self.menubar)
        self.menu_Edit.setObjectName(u"menu_Edit")
        self.menu_Selection = QMenu(self.menubar)
        self.menu_Selection.setObjectName(u"menu_Selection")
        self.menu_View = QMenu(self.menubar)
        self.menu_View.setObjectName(u"menu_View")
        self.menu_Go = QMenu(self.menubar)
        self.menu_Go.setObjectName(u"menu_Go")
        self.menu_Debug = QMenu(self.menubar)
        self.menu_Debug.setObjectName(u"menu_Debug")
        self.menu_Terminal = QMenu(self.menubar)
        self.menu_Terminal.setObjectName(u"menu_Terminal")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.dial, self.verticalSlider)
        QWidget.setTabOrder(self.verticalSlider, self.spinBox)
        QWidget.setTabOrder(self.spinBox, self.doubleSpinBox)
        QWidget.setTabOrder(self.doubleSpinBox, self.horizontalSlider)

        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_Selection.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Go.menuAction())
        self.menubar.addAction(self.menu_Debug.menuAction())
        self.menubar.addAction(self.menu_Terminal.menuAction())
        self.menu_File.addAction(self.action_New_File)
        self.menu_File.addAction(self.action_New_Window)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Open_File_2)
        self.menu_File.addAction(self.action_Open_Folder_2)
        self.menu_File.addAction(self.action_Open_Workspace_2)
        self.menu_File.addAction(self.action_Open_Recent_2)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Add_Folder_to_Workspace)
        self.menu_File.addAction(self.action_Save_Workspace_As)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addAction(self.action_Save_As)
        self.menu_File.addAction(self.action_Save_All)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Auto_Save)
        self.menu_File.addAction(self.action_Preferences)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionRevert_File)
        self.menu_File.addAction(self.action_Close_Editor)
        self.menu_File.addAction(self.action_Close_Workspace)
        self.menu_File.addAction(self.action_Close_Window)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Exit)
        self.menu_Edit.addAction(self.action_Undo)
        self.menu_Edit.addAction(self.action_Redo)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_Cut)
        self.menu_Edit.addAction(self.action_Copy)
        self.menu_Edit.addAction(self.action_Paste)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_Find)
        self.menu_Edit.addAction(self.action_Replace)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_Find_in_Files)
        self.menu_Edit.addAction(self.action_Replace_in_Files)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_Toggle_line_Comment)
        self.menu_Edit.addAction(self.action_Toggle_Block_Comment)
        self.menu_Edit.addAction(self.action_Emmet_Expand_Abbreviation)
        self.menu_Edit.addAction(self.action_Emmet)

        self.retranslateUi(MainWindow)
        self.dial.valueChanged.connect(self.verticalSlider.setValue)
        self.dial.valueChanged.connect(self.progressBar.setValue)
        self.progressBar.valueChanged.connect(self.dial.setValue)
        self.verticalSlider.valueChanged.connect(self.dial.setValue)
        self.dial.valueChanged.connect(self.horizontalSlider.setValue)
        self.dial.valueChanged.connect(self.spinBox.setValue)
        self.spinBox.valueChanged.connect(self.dial.setValue)
        self.doubleSpinBox.valueChanged.connect(MainWindow.setValue)
        MainWindow.valueChanged.connect(self.progressBar.setValue)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.action_New_File.setText(QCoreApplication.translate("MainWindow", u"&New File", None))
        self.action_New_Window.setText(QCoreApplication.translate("MainWindow", u"&New Window", None))
        self.action_Open_File.setText(QCoreApplication.translate("MainWindow", u"&Open File...", None))
        self.action_Open_Folder.setText(QCoreApplication.translate("MainWindow", u"&Open Folder...", None))
        self.action_Open_Workspace.setText(QCoreApplication.translate("MainWindow", u"&Open Workspace...", None))
        self.action_Open_Recent.setText(QCoreApplication.translate("MainWindow", u"&Open Recent", None))
        self.action_Open_File_2.setText(QCoreApplication.translate("MainWindow", u"&Open File...", None))
        self.action_Open_Folder_2.setText(QCoreApplication.translate("MainWindow", u"&Open Folder...", None))
        self.action_Open_Workspace_2.setText(QCoreApplication.translate("MainWindow", u"&Open Workspace...", None))
        self.action_Open_Recent_2.setText(QCoreApplication.translate("MainWindow", u"&Open Recent", None))
        self.action_Add_Folder_to_Workspace.setText(QCoreApplication.translate("MainWindow", u"&Add Folder to Workspace...", None))
        self.action_Save_Workspace_As.setText(QCoreApplication.translate("MainWindow", u"&Save Workspace As...", None))
        self.action_Save.setText(QCoreApplication.translate("MainWindow", u"&Save", None))
        self.action_Save_As.setText(QCoreApplication.translate("MainWindow", u"&Save As...", None))
        self.action_Save_All.setText(QCoreApplication.translate("MainWindow", u"&Save All", None))
        self.action_Auto_Save.setText(QCoreApplication.translate("MainWindow", u"&Auto Save", None))
        self.action_Preferences.setText(QCoreApplication.translate("MainWindow", u"&Preferences", None))
        self.actionRevert_File.setText(QCoreApplication.translate("MainWindow", u"Revert File", None))
        self.action_Close_Editor.setText(QCoreApplication.translate("MainWindow", u"&Close Editor", None))
        self.action_Close_Workspace.setText(QCoreApplication.translate("MainWindow", u"&Close Workspace", None))
        self.action_Close_Window.setText(QCoreApplication.translate("MainWindow", u"&Close Window", None))
        self.action_Exit.setText(QCoreApplication.translate("MainWindow", u"&Exit", None))
        self.action_Undo.setText(QCoreApplication.translate("MainWindow", u"&Undo", None))
        self.action_Redo.setText(QCoreApplication.translate("MainWindow", u"&Redo", None))
        self.action_Cut.setText(QCoreApplication.translate("MainWindow", u"&Cut", None))
        self.action_Copy.setText(QCoreApplication.translate("MainWindow", u"&Copy", None))
        self.action_Paste.setText(QCoreApplication.translate("MainWindow", u"&Paste", None))
        self.action_Find.setText(QCoreApplication.translate("MainWindow", u"&Find", None))
        self.action_Replace.setText(QCoreApplication.translate("MainWindow", u"&Replace", None))
        self.action_Find_in_Files.setText(QCoreApplication.translate("MainWindow", u"&Find in Files", None))
        self.action_Replace_in_Files.setText(QCoreApplication.translate("MainWindow", u"&Replace in Files", None))
        self.action_Toggle_line_Comment.setText(QCoreApplication.translate("MainWindow", u"&Toggle line Comment", None))
        self.action_Toggle_Block_Comment.setText(QCoreApplication.translate("MainWindow", u"&Toggle Block Comment", None))
        self.action_Emmet_Expand_Abbreviation.setText(QCoreApplication.translate("MainWindow", u"&Emmet: Expand Abbreviation", None))
        self.action_Emmet.setText(QCoreApplication.translate("MainWindow", u"&Emmet...", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"GroupBox", None))
        self.menu_File.setTitle(QCoreApplication.translate("MainWindow", u"&File", None))
        self.menu_Edit.setTitle(QCoreApplication.translate("MainWindow", u"&Edit", None))
        self.menu_Selection.setTitle(QCoreApplication.translate("MainWindow", u"&Selection", None))
        self.menu_View.setTitle(QCoreApplication.translate("MainWindow", u"&View", None))
        self.menu_Go.setTitle(QCoreApplication.translate("MainWindow", u"&Go", None))
        self.menu_Debug.setTitle(QCoreApplication.translate("MainWindow", u"&Debug", None))
        self.menu_Terminal.setTitle(QCoreApplication.translate("MainWindow", u"&Terminal", None))
    # retranslateUi

